### ISSUE TITLE
Add Json Visualiser tab to the Details Window

### ISSUE THREAD

**Issue by vocko** [Analogy-LogViewer/Analogy.LogViewer#1002]
Hi Lior,
firstly thanks for an awesome software, I absolutely love your viewer, makes reading logs so much easier.

I'm using it mostly for viewing Serilog logs and would have a small request if it would be possible.

There is Json Visualizer window that you can open and it's my favourite view so far as it is the most human readable presentation of the log information. Would it be possible to add it as a tab to the message details, next to the Formatted Text, Message Text and Message's additional Information. I believe it should not be too complex as all the components already exist and would be a nice addition that will allow to switch between different views.

If not possible, no drama :-)

**Comment by LiorBanai** [comment]
Hi @vocko ,
Sure no problem :).
 I'll add it on this weekend.

**Comment by vocko** [comment]
Great, thanks @LiorBanai

**Comment by LiorBanai** [comment]
HI @vocko ,
I think the best way to add it is as separate UI Element and not in a tab:
![analogy_Detailed](https://user-images.githubusercontent.com/36262995/119122686-7131f880-ba37-11eb-8faf-e241cf092ff8.gif)

this will be active only when the message has json raw data..

what do you think?

**Comment by vocko** [comment]
Hi @LiorBanai,

it looks good and works for me. Might be a little issue on a small screen, but that's generally not a developer's problem :-)

Can't wait to see it in real :-)

**Comment by LiorBanai** [comment]
Will release it tomorrow. Was busy this week..

**Comment by LiorBanai** [comment]
released :)
feel  free to request other changes that may help you

**Comment by vocko** [comment]
Excellent, it works absolutely great, thanks heaps!

I admire where you take time to do all this as I suppose you have a normal full-time job for living. Great work.
