### ISSUE TITLE
Watch or tail?

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer#1015]
### Question

Sorry, I really tried but I did not manage to find an answer. Is there a way to watch a seriog file? I mean update the view in the application without having to press "refresh" all the time?

/ Markus

**Comment by LiorBanai** [comment]
Hi @enkelmedia ,
you can use the File pooling option to refresh to log when the file has changed:
![image](https://user-images.githubusercontent.com/36262995/120752932-1c9c7c00-c513-11eb-884d-b1d76516af88.png)

**Comment by enkelmedia** [comment]
I knew that the solution was just in front of my eyes 😂

Thank you so much!

**Comment by LiorBanai** [comment]
maybe I should rename it to File monitoring or add tooltip since it is not straightforward it seems :)

**Comment by enkelmedia** [comment]
I did actually look at that option in the ribbon before asking the question, I think that a tooltip would be sufficient. That would make it more clear =D
