### ISSUE TITLE
Local time for UTC timestamps

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer#1016]
### Question

I have a question around dates as in this issue, https://github.com/Analogy-LogViewer/Analogy.LogViewer/issues/154 but in my case the timestamps in the log files is UTC-time (using Serilog), is there a way to adjust the "Date"-column to show the local time based on the UTC-stamp?

If not I would be open to contribute with some kind of setting if that would be something that you would like to add.

**Comment by LiorBanai** [comment]
Yeah I think checkbox specifying if it is utc or not  or option to add offset will be beneficial to the users.

**Comment by enkelmedia** [comment]
Sweet! Question is where to put this? As i guess it is not a ”general setting” as some logs might be utveckla and others is in local time. So its a ”per log file” setting I guess? 

What do you think? Where should this be placed?

**Comment by LiorBanai** [comment]
You raise a very good question and I actually need to give this a thought.. it is possible that we may need to expand the Analogy.Interface assembly to get to datetime specification from the data provider (serliog, nlog, etc).. But my guess is that most  people are using single log format so in theory the new settings could be at at application level settings and not per provider..

need to think about it :)

**Comment by LiorBanai** [comment]
I think offset control will be the best. It gives the most flexibility to the end user to change the messages:
![image](https://user-images.githubusercontent.com/36262995/122447154-1e9f1a00-cfac-11eb-933f-4ed0f46fe5e3.png)

**Comment by enkelmedia** [comment]
Thanks for keeping this one alive.

It sounds like a good idea, I just have one question or doubt around this and that would be if one looks at different types of logs, let’s say that some already are in local time, others in UTC - have to jump back and fourth to the settings might not be the best experience.

But on the flip side I don’t really have a great alternative idea, maybe what you proposed on the beginning having a checkbox or “toggle” in the ribbon to quickly switch between the “modes”, or maybe in the statusbar.. who knows? :)

**Comment by LiorBanai** [comment]
Well many logs are indeed UTC so there is a benefit to have direct option to switch between utc and local time.

**Comment by enkelmedia** [comment]
Sounds very nice! 

Where could we put this?

**Comment by LiorBanai** [comment]
I think an option per file loaded is the best:
![image](https://user-images.githubusercontent.com/36262995/122462444-45b21780-cfbd-11eb-8584-8f17aba6ff55.png)

**Comment by LiorBanai** [comment]
I have released a version with the offsets added:
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.7.2

you can find it under the gear icon:
![image](https://user-images.githubusercontent.com/36262995/122640231-127b9f80-d107-11eb-94b3-ad1a311cb64f.png)

**Comment by enkelmedia** [comment]
Works like a charm on the .NET 5-version!
