### ISSUE TITLE
Allow copy values from the json formatted view

### ISSUE THREAD

**Issue by vocko** [Analogy-LogViewer/Analogy.LogViewer#1018]
Follow up to the Json formatted view. 

I've noticed that in the json formatted view, I can't copy the property value. Even selecting the row and using ctrl+c doesn't work. This would be very useful feature. Either a context menu on right mouse click would do, or even just make the shortcut working would help a lot.

Also, opening a view for a particular property would be useful when the value is long (ie. stack trace). At the moment the only option to see the whole content is hover over it and then it displays the content in the tooltip, however, it is not the most user friendly to work with (non saying if I want to copy some part of the content).

If you get a little bit of time, these small things would improve usability a lot :-)

Thanks in advance,
Vocko

**Comment by LiorBanai** [comment]
it is very easy to add copy functionality. Will add it in the coming days

**Comment by LiorBanai** [comment]
@vocko Can you add screenshot of situation where the property is long and how it is currently shown?

**Comment by vocko** [comment]
It looks like this - single line or multi line. An option to open it in a simple text view would be helpful for these cases.

![display_property](https://user-images.githubusercontent.com/18416791/121441335-f2443600-c9cc-11eb-8455-de6e55685d19.png)
![display_property_2](https://user-images.githubusercontent.com/18416791/121441339-f2dccc80-c9cc-11eb-8574-45aabff0aed9.png)

**Comment by LiorBanai** [comment]
ok not it is clear. I'll add option to copy the Node's text

**Comment by LiorBanai** [comment]
I have added 2 options:
Double click the selected node or just copy the text in the textbox below:
![image](https://user-images.githubusercontent.com/36262995/121655745-81be1780-caa7-11eb-8f15-78a440f0d7a5.png)

**Comment by vocko** [comment]
Excellent, thank you a lot, can't wait when it gets released :-)

**Comment by LiorBanai** [comment]
I have release new version with those changes.
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.7.2

you can test it with this version

**Comment by vocko** [comment]
Perfect, thank you very much!
