### ISSUE TITLE
FileNotFound: System.Drawing.Common

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer#1023]
## Describe the bug

When I open a log file using "Open Files" or "File Pooling" I get this error:

![image](https://user-images.githubusercontent.com/1782524/122751488-1a1a8000-d290-11eb-97f8-88415701dfc3.png)

## ℹ Computer information

 - OS: Windows 10 
 - Analogy Version  V4.7.2 on .NET Framework 4.7.2

Edit:

I tried to download the .NET 5-version and in that version I don't get this exception.

**Comment by LiorBanai** [comment]
Thanks for reporting it. I guess I need to test all versions going forward 🙂

**Comment by LiorBanai** [comment]
I have release new version that should fix this.
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.7.3

**Comment by enkelmedia** [comment]
This does work in 4.7.3, but not here is another error

https://github.com/Analogy-LogViewer/Analogy.LogViewer/issues/1030
