### ISSUE TITLE
Error: System.TypeLoadException when opening file

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer#1030]
## Describe the bug
After this bug https://github.com/Analogy-LogViewer/Analogy.LogViewer/issues/1023 was solved I get another error when opening a file.

Version: 4.7.3 on .NET Framework 4.7.2 (also on .NET Framework 4.7.1 and .NET Framework 4.8). .NET 5-version works.

![image](https://user-images.githubusercontent.com/1782524/123089146-ddcd5800-d426-11eb-8262-9fdfcf57eae9.png)

This is when opening a Serilog file, both using "Open Files" and "File Pooling".

**Comment by LiorBanai** [comment]
Interesting :).
I'll check

**Comment by enkelmedia** [comment]
Just forked the repo and tried to run the .NET Framework 4.7.2-version I get the same exception when running the app from Visual Studio "on my machine" =D

I might find time to look closer in some hours

**Comment by LiorBanai** [comment]
very strange is this does not reproduce on my local machine. could be due to having more assemblies in the GAC folder which does not exist in the released version.

**Comment by LiorBanai** [comment]
I does reproduced in clean virtual machine actually :)

**Comment by LiorBanai** [comment]
Ok, Found the issue.. Mismatch in DLLs.. I have uploaded new versions for the .net framework versions. Can you give it a try and see if it works?

**Comment by enkelmedia** [comment]
Works great! I just tested the .NET Framework 4.7.2-version and the error is gone. Thanks a lot!
