### ISSUE TITLE
File dialog not showing all supported formats

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer#1031]
## Describe the bug
I noticied that I always had to write "*" and hit enter in the dialog to find my log files (Serilog files stored as .json).

So I looked at the settings for the serilog parser that looks like this:

![image](https://user-images.githubusercontent.com/1782524/123222304-17a66900-d4d0-11eb-8aee-fdda693161df.png)

Put the "Open File Dialog" does not include the json-format when trying to open a file.

![image](https://user-images.githubusercontent.com/1782524/123222376-2db42980-d4d0-11eb-8db8-e89b3967e154.png)

I might do something wrong or is this a bug? =D

**Comment by LiorBanai** [comment]
don't forget the dialog above the highlighted (the Open file filter). You need to fill both textboxes: one for the file open dialog and one for the parser itself

**Comment by enkelmedia** [comment]
@LiorBanai haha! Sorry! My bad!
