### ISSUE TITLE
JSON log per line

### ISSUE THREAD

**Issue by biiiipy** [Analogy-LogViewer/Analogy.LogViewer#1039]
Is there support for JSON logs where every line is a seperate JSON?
```
{msg: "log"}
{msg: "log2"}
{msg: "log3"}
```

**Comment by LiorBanai** [comment]
Hi @biiiipy ,
Serilog parser support single Json Per line:
https://github.com/Analogy-LogViewer/Analogy.LogViewer.Serilog

Does this meet your needs?

**Comment by biiiipy** [comment]
oh cool, thanks, I'll check it out! Didn't think to look at Serilog parser, cause I'm using NLog for logging :)
Thanks!

**Comment by LiorBanai** [comment]
It may not work since Serilog needs specific key words But I can extend the NLog to read the json.
or better yet, I can update the Generic Json Parser to handle this job:
https://github.com/Analogy-LogViewer/Analogy.LogViewer.JsonParser

I'll check during the weekend and update you :)

**Comment by biiiipy** [comment]
that would be fantastic :)

**Comment by LiorBanai** [comment]
sorry for the late response.
Not sure if this still relevant but in the latest version the new json parser allows to parse but single json or json per file  and you can map fields to the Analogy fields:
![image](https://user-images.githubusercontent.com/36262995/129394349-ade45f20-074c-461c-8b23-cfb0a1a6f48f.png)

**Comment by biiiipy** [comment]
Thanks, it works wonderfully!
