### ISSUE TITLE
Serilog file can't be parsed on Windows Server

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer#1046]
## Describe the bug
I'm running v 4.7.3 of Analogy and try to open a log file on a Windows Server 2019-machine, I'm getting this error:
```
File is not supported by Analogy.LogViewer.Serilog.IAnalogy.OfflineDataProvider. File: C:\Octopus\Applications\Production\....TraceLog.WEB2019.20210710.json
```

The same file can be open just fine on my dev-machine (Windows 10) which seems strange. It's the exact same version of Analogy since I just used the same ZIP-file for both machines.

I can't seem to get more information about the error so I'm wondering if there is any log etc. can be looked at for an error like this?

## ℹ Computer information
 - OS: Windows Server 2019 (DataCenter edition)
 - Analogy Version 4.7.3 (.NET Framework 4.7.2)

**Comment by LiorBanai** [comment]
it seems the user setting has not being set?
can you check the supported file format settings:
![image](https://user-images.githubusercontent.com/36262995/125286182-2be9c300-e324-11eb-8322-9737197ae5a6.png)

**Comment by LiorBanai** [comment]
Any update on this?

**Comment by enkelmedia** [comment]
Sorry. I'm still on summer holiday, back next week and will let you know. Cheers!

**Comment by LiorBanai** [comment]
no problem, enjoy your holiday :)

**Comment by enkelmedia** [comment]
Indeed, it was the settings =D Sorry!

I'm using Umbraco CMS that outputs all serilog-files as .json files, so I had to update the settings to :

```
All Supported formats (*.Clef;*.log;*.gz)|*.clef;*.log;*.gz|Clef format (*.clef)|*.clef|Plain log text file (*.log)|*.log|GZIP file (*.gz)|*.gz|JSON file (*.json)|
```

And

```
*.Clef;*.log;*.gz;*.json
```
