### ISSUE TITLE
NullReferenceException when opening List of Providers

### ISSUE THREAD

**Issue by rose-a** [Analogy-LogViewer/Analogy.LogViewer#1183]
## Describe the bug
On opening up *Settings* -> *Data Providers* -> *List Of Providers* I get a `NullReferenceException` (see Screenshot)

This happens with the freshly dowloaded zip from the [latest release](https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.8.0)

On the second attempt to open the *List Of Providers* (without closing the Settings dialog) I get some "half built" ui (see second screenshot)

## ℹ Computer information

 - OS: Windows 10 Version 21H2 64 bit (Build 19044.1348)
 - Analogy Version: v4.8.0.0 (.NETCoreApp,Version=v6.0)

## 📝 Provide detailed reproduction steps (if any)

1. Open up the Settings Dialog
2. Klick on *List Of Providers* 

### ✔️ Expected result

I can see a "list of providers" 😉 

### ❌ Actual result

See following screenshot.

### Exception on first attempt
![grafik](https://user-images.githubusercontent.com/15836594/146355938-4c3c3e54-091a-4448-9019-9eb0289a3800.png)

### UI on second attempt
![grafik](https://user-images.githubusercontent.com/15836594/146356453-15dbf652-833d-4711-835b-767f7e1ee3aa.png)

**Comment by LiorBanai** [comment]
@rose-a , Thanks for reporting this. I'm able to reproduce it on my end :)

**Comment by LiorBanai** [comment]
I have released new version that fixes this issue. You can download it from the release section 🙂

**Comment by rose-a** [comment]
Yup, fixed!
