### ISSUE TITLE
Storing Filters/Views between application launches

### ISSUE THREAD

**Issue by mudnug** [Analogy-LogViewer/Analogy.LogViewer#1304]
### Question

[I'm using the Serilog Parser]
If I specify some filter parameters, they are remembered between application launches. 
Can I store separate filter criteria (I call these views) and toggle between them?

For example, say one view filters 'text contains sampletext' and another view filters 'text contains othersample' can I switch between these filters/views or do I need to recreate the filter I want every time?

**Comment by LiorBanai** [comment]
Hi @mudnug 
there are two options:
If you enable 'save searches" in the application Settings -> General settings then every time you type a search and press enter it will be saved as auto completion:

![image](https://user-images.githubusercontent.com/36262995/171986122-8f32ada4-7e75-45f3-a00b-7796cad380a2.png)

see full example:
![saveFilters](https://user-images.githubusercontent.com/36262995/171986132-69e99547-d812-431a-81cb-27be4464e7fb.gif)

another option is to use the predefined filters:
![image](https://user-images.githubusercontent.com/36262995/171986190-2b4086e9-3037-4d3c-bf40-d9923c68d9d3.png)


once you defines some filter you can used the in the filter button:
![image](https://user-images.githubusercontent.com/36262995/171986241-ff4fd8c1-9a21-4665-aae6-7c35bdf06ffc.png)

does this meet your needs?

**Comment by LiorBanai** [comment]
maybe it better to have that setting (save last x searches) enabled by default..

**Comment by mudnug** [comment]
Thank you, this does meet my needs and answer the question.

I found a bugs with the pre-defined filters button: The menu appears too far off window

![image](https://user-images.githubusercontent.com/859143/171999990-1a647833-239e-42be-a487-1d870c076fef.png)
It's on the far right of the monitor instead of near the button

**Comment by LiorBanai** [comment]
Thanks. I'll look into it. Already opened new issue to make to popup menu more friendly and not to large.
