### ISSUE TITLE
Update button is unreadble

### ISSUE THREAD

**Issue by mudnug** [Analogy-LogViewer/Analogy.LogViewer#1316]
## Describe the bug
Button/text color has little contrast

## ℹ Computer information

 - OS: [e.g. Windo1 10 Version 1909 64 bit]
 - Analogy Version [e.g. 4.2.3 .NET Core 3.1 or 4.2.3 .NET framework 4.7.2]

## 📝 Provide detailed reproduction steps (if any)

1. Launch older version of app
2. Choose DevExpress Dark Style

### ✔️ Expected result

highlight color is customized to skin

### ❌ Actual result

![image](https://user-images.githubusercontent.com/859143/172251373-75ea593c-4e2a-4b1b-ac96-978450fc13bd.png)

**Comment by LiorBanai** [comment]
Thanks. I saw it in the past but never gave it much priority since most don't use the dark mode i Think
