### ISSUE TITLE
Exception "Controls created on one thread cannot be parented to a control of a different thread."

### ISSUE THREAD

**Issue by chraxo** [Analogy-LogViewer/Analogy.LogViewer#1496]
## Describe the bug
After extracting and starting Analogy LogViewer for the first time an exception window is shown.

## ℹ Computer information

 - OS: Windows 10 Pro, Version	21H2, OS build	19044.2130
 - Analogy Version 4.9.1 .Net 6

## 📝 Provide detailed reproduction steps (if any)

1. Extract Analogy LogViewer + start it.
2. An exception window pops up.

### ✔️ Expected result

* No Exception

### ❌ Actual result

* An exception window pops up.
* After accepting the popup Analogy LogViewer seems to work properly. (At least as far as I can tell as a beginner with Analogy Log Viewer).

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/20266035/197336530-fe8c6339-534e-4280-90d8-96e2d1ec4362.png)

**Comment by LiorBanai** [comment]
Hi @chraxo 
thanks for reporting this. I'll try to reproduce it.
Did it happen only once?
