### ISSUE TITLE
Add an option to display date/time in local pattern

### ISSUE THREAD

**Issue by atzilik** [Analogy-LogViewer/Analogy.LogViewer#154]
Sometimes the date and time are being displayed in an unfamiliar way to theuser

I suggest to add an option to overwrite the log file date/time display pattern settings and convert it to the local pattern. (As configured in the OS where the Analogy is installed on).

**Comment by LiorBanai** [comment]
This issue will be split to:
1. Bug in detailed messages (#156 )
2. this issue which will be use for the ability to set local datetime in grid/Message window

**Comment by LiorBanai** [comment]
anew settings was added to specific different datetime format:
![datetimeformat](https://user-images.githubusercontent.com/36262995/81470495-b0f2bd00-91f3-11ea-970d-6af361fde6c0.jpg)
