### ISSUE TITLE
Open new logs as new tabs in the same application instance

### ISSUE THREAD

**Issue by atzilik** [Analogy-LogViewer/Analogy.LogViewer#155]
Currently when a user opens a log file from the Windows Explorer, a new instance of Analogy is created and a single tab is opened with the log. This process may take quite a while if you are just seeking for the log file you are looking for.

Add to user settings the option to open new log file in a new tab in the same application instance. It would save time and make it easier to navigate between the logs, and above all make use of the tabs which are already there :)

**Comment by LiorBanai** [comment]
Nice usability improvement
