### ISSUE TITLE
Add a multiline value preview to the JSON inline viewer

### ISSUE THREAD

**Issue by montoner0** [Analogy-LogViewer/Analogy.LogViewer#1611]
**Is your feature request related to a problem? Please describe.**
In the JSON inline viewer I can't preview nor copy a long log entry value. The existing tooltip is usually cut out in case of long values.

**Describe the solution you'd like**
Add a multiline value preview as in non-inline viewer.

**Describe alternatives you've considered**
Probably, a multiline tooltip which doesn't cut out and additional context menu to copy the value would also work.

**Additional context**
![image](https://user-images.githubusercontent.com/13542804/214285508-af7e4936-4169-4c90-b9ab-9e342cc8f25e.png)

**Comment by LiorBanai** [comment]
@montoner0 sure, no problem to add it.

**Comment by LiorBanai** [comment]
related to  Refactor Json Viewer #1614

**Comment by LiorBanai** [comment]
hi @montoner0 
is this what you wanted?
![image](https://user-images.githubusercontent.com/36262995/215270384-e7b14614-e437-401d-b8df-bd5580e35fed.png)


Also I'm adding more options for copying and other operations

**Comment by montoner0** [comment]
@LiorBanai Exactly! Many thanks!

**Comment by LiorBanai** [comment]
Great. I'll work on the other issue and after that will release new version

**Comment by LiorBanai** [comment]
fixed and will be released as part of  V4.11.0
