### ISSUE TITLE
'View in Json Visualizer' no longer displays 'tree view' in latest update 4.11.0

### ISSUE THREAD

**Issue by sabasjon** [Analogy-LogViewer/Analogy.LogViewer#1620]
Just to let you know, on previous version (4.10.2.0) when using the Serilog Parser, if we clicked on a line from the log file and then selected 'View in Json Visualizer' (at the bottom of the screen) then a Json Viewer pop up dialog would appear with the JSON and then a tree representation of the JSON

<img width="915" alt="image" src="https://user-images.githubusercontent.com/11357950/217563268-7f6fb8fb-864b-4731-a534-a9d385cb5adf.png">

I have just updated to 4.11.0 and when we select the same button, the Json Viewer popup no longer shows the Tree view.

![image](https://user-images.githubusercontent.com/11357950/217563488-3ed019ea-3683-4f30-b60a-1f544a465d70.png)

I see one of the updates to 4.11.0 was surrounding the Refactoring of the JSON Viewer (issue 1614) so imagine this is related to that work perhaps.  It seems the 'inline JSON Viewer' still works in both versions - so it is just the Json Viewer pop up dialog that has lost this functionality ?

**Comment by LiorBanai** [comment]
this is regression bug. plain and simple :)
thanks for reporting this
