### ISSUE TITLE
Welcome/setup form isn't showing any extension

### ISSUE THREAD

**Issue by pybride** [Analogy-LogViewer/Analogy.LogViewer#1724]
## Describe the bug
The new setup window permits the configuration of extension, but the list is empty. When the application is then opened, its options show them correctly.

### ✔️ Expected result

List all the available extensions (example and LoggersTree)

### ❌ Actual result

Empty list

**Comment by LiorBanai** [comment]
thanks for reporting this.
I'll review the others PR over the weekend :)
