### ISSUE TITLE
Message viewer doesn't understand Linux-style new lines

### ISSUE THREAD

**Issue by montoner0** [Analogy-LogViewer/Analogy.LogViewer#1770]
## Describe the bug
When a log message contains Linux-style new lines (\n instead of \r\n) they aren't rendered as new lines in the message viewers.

## ℹ Computer information

 - OS: Windows 10 Version 22H2 64 bit
 - Analogy Version: 4.14 .NET framework 4.8
 - Data Provider used: Serilog

## 📝 Provide detailed reproduction steps (if any)

1. Open 1.clef from the attached zip in Serilog Parser and click a message
2. The message is shown as in the screenshot 1 below (no distinctive new lines)
3. Open 2.clef from the attached zip in Serilog Parser and click a message
4. The message is shown as in the screenshot 2 below (new lines are clearly present)

### ✔️ Expected result

1.clef and 2.clef are rendered the same way

### ❌ Actual result

1.clef and 2.clef are rendered differently

## 📷 Screenshots
![image1](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/13542804/e8044a70-205c-45bc-a57a-4689114eff41)
![image2](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/13542804/c5b10a9b-42c0-468d-b2ca-55f54219169a)

[logz.zip](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/11938231/logz.zip)

**Comment by LiorBanai** [comment]
Interesting. 
it seems even Devexpress has no solution beside replacing the text.
https://supportcenter.devexpress.com/ticket/details/t1153819/re-newline-character-in-memoedit

I'll check options to handle it.

Thanks for reporting this.

**Comment by LiorBanai** [comment]
I'm considering adding toggle in the UI which will enable the user to switch between styles. Always doing it, or checkeding,  when not needed may impact performance

**Comment by montoner0** [comment]
It's not ideal but still better than nothing. 
What's interesting that tooltips treat the new lines properly.
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/13542804/c91f82b8-59b0-4b73-87a1-0980cb064cc9)

**Comment by LiorBanai** [comment]
I'll check how Devexpress implemented the tool tip. Maybe it will give  idea how to do it automatically.

**Comment by LiorBanai** [comment]
@montoner0  
I have implemented a custom parser. Should be released in the coming days :)
