### ISSUE TITLE
Analogy hangs on huge exception messages

### ISSUE THREAD

**Issue by montoner0** [Analogy-LogViewer/Analogy.LogViewer#1781]
## Describe the bug
When a message is a pretty large exception the application hangs.

## ℹ Computer information

 - OS: Windows 10 Version 22H2 64 bit
 - Analogy Version: 4.14 .NET framework 4.8
 - Data Provider used: Serilog

## 📝 Provide detailed reproduction steps (if any)

1. Open error.clef from the attached archive

### ✔️ Expected result

The application doesn't hang (at least it should show some progress indication and allow to cancel)

### ❌ Actual result

The application hangs (it's unresponsive for about 5 minutes and fully consuming a single CPU core time)

[error.clef.zip](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/12078248/error.clef.zip)

**Comment by LiorBanai** [comment]
hi @montoner0 
i'll check it this weekend . Thanks for reporting

**Comment by LiorBanai** [comment]
I'm able to reproduce it. a fix should be easy to implement

**Comment by LiorBanai** [comment]
Releasing new version today
