### ISSUE TITLE
Exception in LogMessagesUC's LogGrid_CustomSummaryCalculate during/after Time Difference calculation

### ISSUE THREAD

**Issue by Benedicht** [Analogy-LogViewer/Analogy.LogViewer#1839]
## Describe the bug

I have an >50 Mb json file that i load with Json Log Parser. Right clicking and selecting `Calculate time difference from this point` throws a `System.ArgumentNullException` in `LogMessagesUC.LogGrid_CustomSummaryCalculate` at line 1138:

https://github.com/Analogy-LogViewer/Analogy.LogViewer/blob/3048699f29c5e7fcbd4446e634641f68e6ffe0ba/Analogy.CommonControls/UserControls/LogMessagesUC.cs#L1136-L1139

Tried out both the pre-built [v4.14.1](https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.14.1) version and latest bits pulled down from the git repo. Both of them gave the very same result.

## ℹ Computer information

 - OS: Windows 10 Pro 19042.450 64 bit
 - Analogy Version: Both latest pre-built release and source built using .NET Core 7
 - JSon Data Provider

## 📝 Provide detailed reproduction steps (if any)

1. Load the attached [top500_Timered.json](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/12507347/top500_Timered.zip)
2. Right-click on the first row.
3. Select `Calculate time difference from this point` menu item
4. Exception thrown in the above mentioned line

### ✔️ Expected result

Calculate time difference.

### ❌ Actual result

Exception thrown.

## 📷 Screenshots

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/4248416/f81d7aa1-2495-4438-b498-f41528f83237)

[top500_Timered.zip](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/12507347/top500_Timered.zip)

**Comment by LiorBanai** [comment]
@Benedicht thanks for reporting. I'll check this

**Comment by Benedicht** [comment]
Thanks! Let me know if i can add any more details.

**Comment by LiorBanai** [comment]
I see you are using the json parser. Can you please add the mapped fields you are using so I can reproduce it faster

**Comment by Benedicht** [comment]
All json objects in the file should have both the `date` and `level` fields, no mapping should be needed.

**Comment by LiorBanai** [comment]
ok thanks. I'll update :)

**Comment by Benedicht** [comment]
I have tested your commit and it's working correctly, thanks!
