### ISSUE TITLE
Why NLog does not work and all others at minimum should be able to provide unfiltered raw view?

### ISSUE THREAD

**Issue by BirukTes** [Analogy-LogViewer/Analogy.LogViewer#1862]
#### Viewer 5.1.0 Net48

Why NLog does not work and all others at minimum should be able to provide unfiltered raw view?
- The reason minimum of raw view should be available is so that we do not have to go to VS Code or other better text editor to view to view it, although the VS code does a good job of tokenization which is very helpful.
- The raw view button shows this:
`File is not supported by Analogy.LogViewer.NLogProvider.NLogDataProvider. File: D:\Downloads\Data\Logs\error-2023-10-03.log`

#### Errors:
Whenever something is being saved in the NLog settings this error is also showing which sometimes ignores it.
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/23151263/967723ec-0c4c-4e75-9fe7-c89f6035f25f)
Other NLog errors after playing around with some settings, this error is showing for all providers and can be reset by deleting user config:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/23151263/3897b30c-7c49-4370-96e1-b95e1e82669b)

**Comment by LiorBanai** [comment]
Hi @BirukTes Nlog should be fully supported.
can you attach log for me to test it and fix the issue?

**Comment by BirukTes** [comment]
Hi @LiorBanai,
Try this file:
[all-2023-10-09.log](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/12894878/all-2023-10-09.log)

**Comment by LiorBanai** [comment]
@BirukTes Working on this. Will update

**Comment by LiorBanai** [comment]
already have some fixes.. still will imrpove it more

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/7ee24613-2338-48a8-9ad3-bc1b712aec8b)

**Comment by LiorBanai** [comment]
I have a complete fix for this.
I'm working also on #1866  and will release new version probabl over the weekend.

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/285157c9-ddf9-4a4a-b26f-d807326f7f7c)

**Comment by BirukTes** [comment]
Great progress! Thanks

**Comment by LiorBanai** [comment]
I have Released new version. You can test it and report back with any problems :)
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/v5.1.1.0

**Comment by LiorBanai** [comment]
Open the setting in the right and check the mapping of fields... It is kind of mandatory.

I may set default or better message to the user

**Comment by LiorBanai** [comment]
Hi @BirukTes 

The following should work for the above file (all-2023-10-09.log):
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/3000fe9a-962d-42a6-a5b5-f8fb127ea7ec)

Result:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/dc2d8b1d-374b-461f-b756-242e2311d6f6)


I plan to release NET8 version soon so I'll add some instruction how to setup the columm's indexes

**Comment by LiorBanai** [comment]
Intereseting your settings also work.
What is the time format of your OS?

**Comment by BirukTes** [comment]
Hi @LiorBanai, 

Thanks, I am using UK region and culture... so my Windows 10 time format is like: 15/11/2023 20:00:00 or dd/MM/yyyy HH:mm:ss

**Comment by LiorBanai** [comment]
Thanks. I may have better solution. Can you add the nlog message template so I can infer the columns field mapping ad default setting?

**Comment by BirukTes** [comment]
Do you mean our NLog template?
```
layout="${longdate}|${aspnet-traceidentifier}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />
```

**Comment by BirukTes** [comment]
Okay, it seems like Net48 has the most issues/exceptions, and other builds just do not show anything as I have just tested on my machine and Example tab that is provided both the Example 1 and 2.

- It does not seems like there is a way to print all stack trace, which might help you... is there?
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/23151263/529512da-dbb5-4309-80bb-241d1d274c36)

**Comment by LiorBanai** [comment]
Very strange. I'll check this. thanks for updating me!

**Comment by LiorBanai** [comment]
can you zip the fodle C:\Users\XXX\AppData\Local\Analogy.LogViewer\  and attach it. I'm starting to think it is related to specific user settings/preferences..

**Comment by BirukTes** [comment]
Here:
[Analogy.exe_Url_pl1fq2x5xzf3vfhs5p1vsqbuwm30nzjs.zip](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/13440983/Analogy.exe_Url_pl1fq2x5xzf3vfhs5p1vsqbuwm30nzjs.zip)


> can you zip the folder C:\Users\XXX\AppData\Local\Analogy.LogViewer\ and attach it. I'm starting to think it is related to specific user settings/preferences..

**Comment by LiorBanai** [comment]
Thanks. now I'm able to reproduce it. 
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/195297dd-747d-455a-bb1f-eb3d63576c36)

**Comment by LiorBanai** [comment]
It is related to the WXI skin as discussed here
https://supportcenter.devexpress.com/ticket/details/t1098901/tokenedit-maskbox-internal-property-is-null-when-wxi-or-wxi-compact-skin-is-applied

for now you can probably use different skin to resolve it until I'll release a fix for the newly issue #1899

**Comment by BirukTes** [comment]
So, I tried the 'Basic' theme, and the same result as other builds without exception but not logs parsed:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/23151263/fae95142-831d-4f91-bada-5e0dfe2f7914)

**Comment by LiorBanai** [comment]
Does more-> Windows Layouts -> Default fix this?
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/bbbfe993-e041-45f0-9211-ba9c2ce7fb97)

**Comment by BirukTes** [comment]
Now, briefly, I can see something displaying in the logs panel/area, which I managed to screenshot but stays only for 1 sec.
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/23151263/8dd73c33-3109-4baa-b066-7f4b7e57c4cc)

**Comment by LiorBanai** [comment]
could be. I'll investigate.
