### ISSUE TITLE
millisecond time is not showing parsed json record.

### ISSUE THREAD

**Issue by vgitk** [Analogy-LogViewer/Analogy.LogViewer#1866]
### Question

Shalom,

I've recently come across a fantastic log-parsing tool. I need to parse extensive .log files containing JSON records on each line.

I'm attempting to parse JSON files using the "JSON log parser." I've configured the dateTime format as "yyyy.MM.dd HH:mm:ss.fff," but I'm encountering an issue where the millisecond time isn't visible in the output.

Sample JSON record1 :

`{"instant":{"epochSecond":1685544384,"nanoOfSecond":611206994},"thread":"taskScheduler-3","level":"DEBUG","loggerName":"com.corp.cbu.cnc.nrfc.NRFCManagement","message":"NfInstanceId c1b51db4-7ac6-11ec-90d6-0242ac120003 present in list of configuredNfProfiles","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":54,"threadPriority":5,"messageTimestamp":"2023-05-31T14:46:24.611+0000"}`
`
Sample JSON record2 :

`{"messageTimestamp":"2023-05-31T15:06:10.497Z","logLevel":"DEBUG","pid":1,"workerId":"master","message":"Fetching data from URI: http://occnp-2310-26507-gyltj-occnp-config-server:8000/topics/common.logging.pre for topic common.logging.pre with param false"}`

DateTime format:

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/69047906/5949877d-fc3f-47d6-892a-b4548e1ac52c)

If you observe, the time format in both the sample records is slightly different.

Sample 1 messageTimestamp : 2023-05-31T14:46:24.611+0000
Sample 1 messageTimestamp : 2023-05-31T15:06:10.497Z

We receive both types of files for analysis, and we need to correlate the records between these two file formats. I would greatly appreciate it if you could recommend a method for extracting the date and time from both types of records and displaying them in the "yyyy.MM.dd HH:mm:ss.fff" format.

JSON configuration:

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/69047906/8bee5864-b5f3-473d-919a-ce361f04d70e)

Here is the parsed record view, for some reason, it does not show the millisecond time. 

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/69047906/01683b23-6728-4db8-96c1-66a292bb640d)

Looking forward to hearing from you.

**Comment by vgitk** [comment]
This is the error that I can see : 

Error: error: Input string was not in a correct format.. Member:. Line:0. Thread (managedID):1. Start Time:10/22/2023 1:38:27 AM. Time:10/22/2023 01:38:39.126 AM. File: . Exception: System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(FormattedLogValues state, Exception error)
   at Analogy.AnalogyLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter). Member:. Line:0. Thread (managedID):1. Start Time:10/22/2023 1:38:27 AM. Time:10/22/2023 01:38:39.126 AM. File:

**Comment by LiorBanai** [comment]
Hi @vgitk 
This should be relative simple fix. I'll check this and update you.

**Comment by vgitk** [comment]
Hi Lior,

Thank you so much for your help!

**Comment by LiorBanai** [comment]
Hi @vgitk 
with this example
```json
{"instant":{"epochSecond":1685544384,"nanoOfSecond":611206994},"thread":"taskScheduler-3","level":"DEBUG","loggerName":"com.corp.cbu.cnc.nrfc.NRFCManagement","message":"NfInstanceId c1b51db4-7ac6-11ec-90d6-0242ac120003 present in list of configuredNfProfiles","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":54,"threadPriority":5,"messageTimestamp":"2023-05-31T14:46:24.611+0000"}
{"messageTimestamp":"2023-05-31T15:06:10.497Z","logLevel":"DEBUG","pid":1,"workerId":"master","message":"Fetching data from URI: http://occnp-2310-26507-gyltj-occnp-config-server:8000/topics/common.logging.pre for topic common.logging.pre with param false"}
```

after small tweak  and update in Analogy the format, I'm getting this:

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/959ffde0-2425-4ed5-a2d0-ed34869a46f6)

and formating:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/a5ed7757-9a87-4408-83e5-ece80050e432)

Is this what you need?

**Comment by vgitk** [comment]
Hi @LiorBanai,

Thanks for your efforts, yes the change looks good to me. I assume the change can handle the date and time below formats:

Sample 1 messageTimestamp : 2023-05-31T14:46:24.611**+0000**
Sample 2 messageTimestamp : 2023-05-31T15:06:10.497**Z**

basically in the final output I need the date and time below format: 

yyyy-MM-DDTHH:mm:ss.fff (milliseconds in three decimal digits)

**Comment by LiorBanai** [comment]
so it seems the solution is working:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/b0350735-15e5-414e-a0d8-5b0cf42a9e03)


I have used the follownig format:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/789b5c67-935e-467e-b22e-00c63aeadea1)

will release new version later today.

**Comment by LiorBanai** [comment]
I have Released new version. You can test it and report back with any problems :)
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/v5.1.1.0

**Comment by vgitk** [comment]
Awesome, thanks for the update!

I have checked it's working now.

- Vivek
