### ISSUE TITLE
String Format Exception on launch of v6.0.0 on .net 4.8

### ISSUE THREAD

**Issue by sabasjon** [Analogy-LogViewer/Analogy.LogViewer#1936]
I have upgraded to the latest version 6.0.0 using the net4.8 zip version and each time I open the application we now get a 'Error: System.FormatException: Input string was not in a correct format' prompt immediately on screen (screen shot below/attached)

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/11357950/3f23e3dc-bca0-400a-b099-ed6ccdbf0eea)

I tried to completely remove the application and perform a fresh download/unzip in case it was something left over from previous version running, however same issue presents itself.

We see a similar error when clicking on other menu items so - for example, if we try and adjust the template then we get a longer error prompt on screen, but is related to the first issue about 'Version'

![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/11357950/86343240-6003-4667-9d14-4348d40613aa)

## ℹ Computer information

 - OS: Windows 10 (10.0.19045)
 - Analogy Version 6.0.0 using .net 4.8 release on .net framework 4.8
 - Data Provider used - N/A as error occurs as soon as application opens on screen

**Comment by LiorBanai** [comment]
@sabasjon Very strange.
I'll investigate.
What happens if you completely delete the C:\Users\XX user XX\AppData\Local\Analogy.LogViewer  folder and try agian?

**Comment by sabasjon** [comment]
@LiorBanai  Thanks for the response, I have now tried to delete the above folder and relaunched, however the same error message is presented when the application opens

Cheers

**Comment by LiorBanai** [comment]
Ok, I'll investigate by end of week. :)

**Comment by opheoHeidrich** [comment]
The Exception is thrown during the update check. The version string for the 6.0 seems to be invalid, likely because the '-0' at the end of 'V6.0.0.0-0' is not valid version syntax and throws an exception in Analogy.Managers.UpdateManager.GetVersionFromTagName.

**Comment by LiorBanai** [comment]
it is importatn enough to release new version. I'll update tomorrow

**Comment by LiorBanai** [comment]
Actually just editing to Tag on Github should resolve this.
@sabasjon can you give it a try now? I have edited the tag

**Comment by sabasjon** [comment]
Hi @LiorBanai - yes that has fixed the issue now - thanks for quick responses :)

**Comment by LiorBanai** [comment]
good to know.
