### ISSUE TITLE
IIS Parser crashes when there are additional fields

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer#1971]
## Describe the bug
We have IIS logs with a "non standard" field "X-Forwarded-For" since the app is behind a proxy.

When opening the file I get:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/1782524/839154a4-204f-4509-9740-8e05166a19df)

```
Reason: The given key 'X-Forwarded-For' was not present in the dictionary.
```

## ℹ Computer information

 - OS: Windows 11
 - Analogy Version 6.0.1 (.NET 8)
 - Data Provider: IIS

## 📝 Provide detailed reproduction steps (if any)

1. Create IIS log with additional fields
2. Open 
3. See error

### ✔️ Expected result

The best solution would probably be if the parser read the fields header where all the fields from the file i represented

```
Header: #Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken X-Forwarded-For
```

Let me know if you need more info or help!

Cheers!

**Comment by LiorBanai** [comment]
Should be easy fix. I'll update

**Comment by LiorBanai** [comment]
@enkelmedia 
I have added the custom parsing as new column:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/111ef4f6-88bb-4061-bd1e-39b0e62ffc66)

also it is added to the text message at the end:
![image](https://github.com/Analogy-LogViewer/Analogy.LogViewer/assets/36262995/adb325f7-f986-43e8-b27d-5635f1fb3f36)

does this meet your need?

**Comment by enkelmedia** [comment]
Fantastic! I’ll give it a try asap :)

**Comment by LiorBanai** [comment]
@enkelmedia I haven't released new version yet :). 
you can the zip filein and replace the dll manually for now..
[Analogy.LogViewer.IISLogsProvider.zip](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/14506059/Analogy.LogViewer.IISLogsProvider.zip)

**Comment by enkelmedia** [comment]
Just tried the new DLL - works great! =D Awesome work!

**Comment by LiorBanai** [comment]
good to know so I'll release is soon as part of the main app.
