### ISSUE TITLE
Main log viewer window always starts up full screen?

### ISSUE THREAD

**Issue by Numpsy** [Analogy-LogViewer/Analogy.LogViewer#213]
I noticed when testing that the main log viewer window always seems to start up in a maximized state (it's a pretty minor thing, but when I open it on a 40" display it's just a bit too large!).

I was just wondering if there is a means to make the Window remember its size across sessions or some such, rather than always using the default?

Thanks.

**Comment by LiorBanai** [comment]
Good idea actually (and relevant one for large monitors).
Right now there isn't a way to do so but it easy to implement.

**Comment by LiorBanai** [comment]
new user setting added (default is On):
![image](https://user-images.githubusercontent.com/36262995/86621800-7f198f00-bfc7-11ea-91c4-dd6120c20c06.png)

**Comment by Numpsy** [comment]
thanks

**Comment by LiorBanai** [comment]
I have 2 more small issues that I plan to fix soon and release new version with those.
