### ISSUE TITLE
Missing PlainTextParser dll on the latest release (4.2.4)

### ISSUE THREAD

**Issue by vocko** [Analogy-LogViewer/Analogy.LogViewer#235]
**Describe the bug**
Getting this on EventLog when trying to run the app. 

Description: A .NET Core application failed.
Application: Analogy.exe
Path: C:\Program Files\Analogy Log Viewer\Analogy.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Analogy.deps.json) was not found:
    package: 'Analogy.LogViewer.PlainTextParser', version: '1.0.9'
    path: 'lib/netcoreapp3.1/Analogy.LogViewer.PlainTextParser.dll'

**To Reproduce**
1. Download and unzip the app
2. Run the app

**Expected behavior**
App starts :-)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Version 2004 64 bit]
 - Analogy Version [4.2.4 .NET Core 3.1 ]

**Comment by LiorBanai** [comment]
Thanks for letting me know!
I have update the [release](https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.2.4). You can retry it.

**Comment by vocko** [comment]
@LiorBanai It is fixed now, thanks.
