### ISSUE TITLE
Searching based on a selected value in a custom column?

### ISSUE THREAD

**Issue by Numpsy** [Analogy-LogViewer/Analogy.LogViewer#271]
A thought that i had while using the 4.2.4 release (I see there have been some search changes recently, so I don't know what the actual unreleased state is), but I did'nt see an option in this version, so:

Say I have something like this log from an ASP.Net Core app:

![image](https://user-images.githubusercontent.com/1178570/88413084-7819bb80-cdd2-11ea-80b5-4ba6ce881b6c.png)

Where all the log entries have a RequestId property that gets set up by ASP itself.
In this trivial case, all the entries for a request are in a stack, but if there are multiple clients hitting the service at once then you might get the logging for many requests all intermixed.

So - I'm wondering if it would be useful to be able to do something like right click on a cell, and launch a search for all matching values from there (any then use that to get the subset of all events that match that one request)?

**Comment by LiorBanai** [comment]
right now I'm in the process of adding in-place search and filter: https://github.com/Analogy-LogViewer/Analogy.LogViewer/issues/269
also right click currently has hard coded Exclude text,source and process/module:
![image](https://user-images.githubusercontent.com/36262995/88415124-a5706480-cde6-11ea-80ec-abf8e13b8d68.png)

do you mean you wish new option Exclude current Cell: XXX where the value will be added to the exclude columns:
![image](https://user-images.githubusercontent.com/36262995/88415379-11eb6380-cde7-11ea-8652-85a47c0a9f79.png)

**Comment by Numpsy** [comment]
In this example, I'm thinking - right click on a row in the RequestId column, and start a search for the text in that cell (so, search for all logs entries whose RequestId is '0HM...' rather than having to enter the text in the search field manually

**Comment by LiorBanai** [comment]
so basically set a filter for that text and in the filtered list start a search/filter:
you can filter most columns by typing a text in the header row:
![image](https://user-images.githubusercontent.com/36262995/88417300-63492200-cdea-11ea-87c6-49273d9125dc.png)

**Comment by Numpsy** [comment]
I hadn't realised that you could do that :-)

**Comment by LiorBanai** [comment]
You can combine both header filters and primary filters. They csn work together.

**Comment by Numpsy** [comment]
So what i'm asking about is just the ability to start a header filter for the text in a selected cell then.

**Comment by LiorBanai** [comment]
I don't understand,  you cannot type filter in the specific column's header with the cell text?

**Comment by Numpsy** [comment]
It's a pretty trivial thing, I just thought it'd be easier when searching/filtering on values that aren't particularly 'friendly', e.g.

![image](https://user-images.githubusercontent.com/1178570/88651619-c3c5b100-d0c1-11ea-8315-7a390df46acf.png)

**Comment by LiorBanai** [comment]
Ah now I understand. Make the process easier /simplify.. 🙂

**Comment by LiorBanai** [comment]
@Numpsy 
is this what you meant?
Right click a cell and thre is a new option to add it to active column filter:
![image](https://user-images.githubusercontent.com/36262995/88954943-d8619f00-d2a3-11ea-9e02-36f24ec05817.png)

**Comment by Numpsy** [comment]
Yes, thanks :-)
