### ISSUE TITLE
[Filtering] Message layout does not affect view and keeps resetting

### ISSUE THREAD

**Issue by EternalClickbait** [Analogy-LogViewer/Analogy.LogViewer#417]
## Describe the bug
Whenever I try to change my message layout, such as hiding the Data source column, it gets hidden in the settings window, but does not affect the main window.

## ℹ Computer information

 - OS: Windows 10 V1909 64-bit (Enterprise)
 - Analogy Version 4.2.7 .Net Core 3.1
 

## 📝 Provide detailed reproduction steps (if any)

1. Open Analogy settings
2. Go to `Filtering and Interactions`
3. Modify a column in some way (in the settings window) e.g. Hide the Data Source column.

### ✔️ Expected result

1. The main window view changes to reflect the changes
and 
2. The settings are saved and show the changes you have made when re-opening them

### ❌ Actual result

1. Nothing happens, and the main window view does not change
and
2. Re-opening the settings window shows the columns have been reset (no changes were made).

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/48875125/92301983-9c5ce080-efab-11ea-82ac-f249ef97fcbc.png)

**Comment by LiorBanai** [comment]
Thanks for reporting this. Renaming columns works but hiding columns indeed does not being set correctly.

**Comment by LiorBanai** [comment]
I fixed the issues and split it to a seconds issue that handles the real time update upon chnages.
BTW if can save yuor changes from the standard window by right clicking and chooses "Save columns layout":
![image](https://user-images.githubusercontent.com/36262995/92309890-e5179800-efb1-11ea-8997-dc7a3d93b962.png)
