### ISSUE TITLE
The OK button on the 'Data Source Information' dialog doesn't seem to do anything.

### ISSUE THREAD

**Issue by Numpsy** [Analogy-LogViewer/Analogy.LogViewer#546]
## Describe the bug
Clicking the 'Data Source Information' button on one of the provider tabs opens a provider About box that contains an 'OK' button, but clicking that button doesn't seem to do anything (the dialog has to be closed with the toolbar 'close' button).

## ℹ Computer information

Analogy 4.2.9 (.NET 4.7.2 build) on Windows 10

## 📝 Provide detailed reproduction steps (if any)

Select one of the provider tabs.
Click the 'Data Source Information' button on the right of the ribbon bar.
Click the 'OK' button at the bottom right of the dialog.

### ✔️ Expected result

I expected the OK button to close the dialog.

### ❌ Actual result

Nothing happens.

**Comment by LiorBanai** [comment]
funny bug :)
