### ISSUE TITLE
4.2.10 UnauthorizedAccessException when closing the app

### ISSUE THREAD

**Issue by vocko** [Analogy-LogViewer/Analogy.LogViewer#568]
## Describe the bug
I can't close the app due to an exception (see attached screenshot). It seems it tries to write to a settings file that lives in the install folder (withing Program Files in my case). If I start the app as an admin, there is no issue. I recommend to move the settings files into c:\Users\Username\AppData\Local\AnalogyLogViewer. In this case you can save settings per user rather than same for all and you will avoid permissions issues.

## ℹ Computer information

 - OS: Windows 10 Version 2004 64 bit
 - Analogy Version 4.2.10 .NET Core 3.1

## 📝 Detailed reproduction steps

1. Install app to a folder with a restricted access (ie. Program Files)
2. Start App
3. Try to close the app

### ✔️ Expected result

App will close with no issues even if run under standard permissions.

### ❌ Actual result

App fails to close on UnauthorizedAccessException .

## 📷 Screenshots

![Capture](https://user-images.githubusercontent.com/18416791/96389718-69d21480-11f4-11eb-8965-853a6119edda.PNG)

**Comment by LiorBanai** [comment]
Good suggestion. Thanks for reporting this.
I normally run as admin so I did not experience this issue.
