### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by danno71** [Analogy-LogViewer/Analogy.LogViewer#822]
### Question

Hello, is it possible to run Analogy on a portable device (e.g. USB stick)? The Analogy settings must then be stored accordingly on the USB stick.

**Comment by LiorBanai** [comment]
Hi @danno71.  Currently the settings are saved under the current user's local folder but it is very easy to add an option to save it under current application folder instead which will serves this use case.

I'll add this this week.

For now you can export/import current settings from the ribbon application menu:

![image](https://user-images.githubusercontent.com/36262995/104840217-adf5b380-58ce-11eb-8d5f-729284f476cf.png)

**Comment by LiorBanai** [comment]
I have added toggle in the application setting window to select portable mode (save setting in the application folder) or per user (current mode).

Doing tests now. I may release this version tomorrow.
![image](https://user-images.githubusercontent.com/36262995/105519699-67df8c00-5ce2-11eb-80bf-98dc12daaa3a.png)

**Comment by LiorBanai** [comment]
@danno71 , I have released new version with portable option added. You can give it a try and if there are issues please report back.
I'll close this issue. Please open new one if problems arise.
