### ISSUE TITLE
json visualiser

### ISSUE THREAD

**Issue by codehunter13** [Analogy-LogViewer/Analogy.LogViewer#886]
In Message info text inside {} is replaced:
![image](https://user-images.githubusercontent.com/7559059/108978851-58a98080-768a-11eb-8718-e6ed7d45e182.png)

i click on view in json visualiser and the following windows opens. Here is the text inside {} NOT replaced.
![image](https://user-images.githubusercontent.com/7559059/108979056-91495a00-768a-11eb-840e-88cb916ca7bd.png)
So the json tree stops at that item. If i replace it manually, the json tree loads correctly.

Am i doing something wrong or is this a bug?
Thx in advance

 - OS: Windows 10 
 - Analogy Version 4.6.1.0 
 - Serilog

**Comment by LiorBanai** [comment]
seems like a bug actually.
can you add the relevant file/json for me to test?

**Comment by LiorBanai** [comment]
Actaully, the Serilog parser may need extra tuning to remove the non json parts.. I will appreciated if you can send me the log file

**Comment by codehunter13** [comment]
[cryptohunter_log_compact20210223.txt](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/6035159/cryptohunter_log_compact20210223.txt)

**Comment by codehunter13** [comment]
its the same log as i reported in item 887. So possibly its also caused by invalid json

**Comment by LiorBanai** [comment]
Thanks!

**Comment by LiorBanai** [comment]
ok it is indeed bug :)
I have a fix. Will release new version on the weekend

![image](https://user-images.githubusercontent.com/36262995/109040098-39384500-76d6-11eb-9801-c4326be156c0.png)

**Comment by LiorBanai** [comment]
@codehunter13 , I have released new version that fixes this issue 
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.6.2

thanks for reporting it.
