### ISSUE TITLE
net48.zip attempted to open a Win10 evtx and got a DevExpress assembly not found error. 

### ISSUE THREAD

**Issue by CyberBitz** [Analogy-LogViewer/Analogy.LogViewer#900]
## ℹ Computer information

 - OS: Win10
 - Downloaded the net48.zip

## 📝 Provide detailed reproduction steps (if any)

imported a win10 evtx

### ✔️ Expected result

opened the viewer
### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

![2021-03-11 14_37_34-Error](https://user-images.githubusercontent.com/582721/110830277-cc957c80-8277-11eb-99f3-712c2b2f8a2d.png)

**Comment by LiorBanai** [comment]
thanks for reporting this.
I'll update the release tomorrow and publish new one.

**Comment by LiorBanai** [comment]
[DevExpress.Office.v19.1.Core.zip](https://github.com/Analogy-LogViewer/Analogy.LogViewer/files/6124987/DevExpress.Office.v19.1.Core.zip)

can you unzip this file to the application folder and check if this solve the issue?

**Comment by LiorBanai** [comment]
@CyberBitz , Did you manage to test this and verify if it work with the missing dll?

**Comment by LiorBanai** [comment]
Closing and no additional input was communicated.
