### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by DanielMorsch** [Analogy-LogViewer/Analogy.LogViewer#904]
## Describe the bug
Crash on start Analogy the first time. 

## ℹ Computer information

 - OS: Win10 20H2
 - Analogy Version 4.6.3 .NET Core 3.1 and .NET framework 4.8
 - 3 Monitors (1st: 3840x2400, 2st+3rd:1920x1200)

## 📝 Provide detailed reproduction steps (if any)

1. Start Analogy.exe
2. Pass through tutorial
3. Crash happens (see screenshot)

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/11983327/111197729-199e8900-85bf-11eb-89af-5ad1d9a6d3fc.png)

**Comment by LiorBanai** [comment]
Hi @DanielMorsch ,
Thanks for reporting this.
can you check if this still happens in 2 monitors setup?

**Comment by LiorBanai** [comment]
And reduce resolution (just for testing)

**Comment by LiorBanai** [comment]
seems same issue In DevExpress support:
https://supportcenter.devexpress.com/ticket/details/q407496/minimumsize-system-argumentoutofrangeexception

**Comment by DanielMorsch** [comment]
Hi, 
i think the problem is the 4k monitor. 
If i reduce the resolution to fullHD it works.
It looks like the same issue in DevExpress.

**Comment by LiorBanai** [comment]
I'll check this tomorrow on a 4k monitor :)

**Comment by DanielMorsch** [comment]
Hi @LiorBanai, 
found a workaround:

Override the Override High DPI scaling behavior inside the Exe Properties and set this to "System" or "System (Enhanced)". 
Then it works.

Regards,
Daniel

**Comment by LiorBanai** [comment]
@DanielMorsch ,
Wow nice found!. :)
I will still try to find a solution in code

**Comment by LiorBanai** [comment]
Does the UI look usable in 4K?

**Comment by DanielMorsch** [comment]
Yeah it will look fine. 
Windows scale automatically if you move it on the 4k monitor.

**Comment by DanielMorsch** [comment]
Maybe its all about this DPI Awareness: 
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8

**Comment by Oscaruzzo** [comment]
Just confirming it happens on 4K displays, both with the .net core 3.1 version and with the .net framework 4.8 version. Override High DPI scaling works, but fonts looks somewhat "grainy"

![image](https://user-images.githubusercontent.com/6238570/114375186-b59ebe80-9b84-11eb-8e43-2ef9c1ea8f34.png)

**Comment by LiorBanai** [comment]
Thanks for informing me. I'll update soon to a newer version of DevExpress and will test it on that version

**Comment by LiorBanai** [comment]
Hi,
I have released new version with new version of DevExpress.
can you please check if this still persist?

**Comment by Oscaruzzo** [comment]
Hi, I can confirm this release https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.7.1 works in 4K resolution without any "compatibility" or "Override High DPI" settings.

Good job, thank you!

**Comment by LiorBanai** [comment]
Great! thanks for the update

**Comment by LiorBanai** [comment]
fixed in V4.7.1
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/V4.7.1
